import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Sembrando catálogo base...');

  const adminUser = await prisma.user.findFirst({
    where: { email: 'superadmin@pae.co' },
  });
  const createdBy = adminUser?.id || '00000000-0000-0000-0000-000000000000';

  // ============================================================
  // UNSPSC - Taxonomía de productos (códigos alimenticios comunes)
  // ============================================================
  const unspscData = [
    { codigo: '10000000', nombre: 'Plantas y materiales vegetales', nivel: 1, padreId: null },
    { codigo: '10100000', nombre: 'Plantas y productos vegetales vivos', nivel: 2, padreId: '10000000' },
    { codigo: '10101500', nombre: 'Frutas', nivel: 3, padreId: '10100000' },
    { codigo: '10101501', nombre: 'Banano', nivel: 4, padreId: '10101500' },
    { codigo: '10101502', nombre: 'Manzana', nivel: 4, padreId: '10101500' },
    { codigo: '10101503', nombre: 'Naranja', nivel: 4, padreId: '10101500' },
    { codigo: '10101504', nombre: 'Papaya', nivel: 4, padreId: '10101500' },
    { codigo: '10101505', nombre: 'Mango', nivel: 4, padreId: '10101500' },
    { codigo: '10101506', nombre: 'Piña', nivel: 4, padreId: '10101500' },
    { codigo: '10101507', nombre: 'Fresa', nivel: 4, padreId: '10101500' },
    { codigo: '10101508', nombre: 'Limón', nivel: 4, padreId: '10101500' },
    { codigo: '10101509', nombre: 'Mandarina', nivel: 4, padreId: '10101500' },
    { codigo: '10101510', nombre: 'Uva', nivel: 4, padreId: '10101500' },
    { codigo: '10101511', nombre: 'Patilla/Sandía', nivel: 4, padreId: '10101500' },
    { codigo: '10101512', nombre: 'Melón', nivel: 4, padreId: '10101500' },
    { codigo: '10101513', nombre: 'Guanábana', nivel: 4, padreId: '10101500' },
    { codigo: '10101514', nombre: 'Lulo', nivel: 4, padreId: '10101500' },
    { codigo: '10101515', nombre: 'Maracuyá', nivel: 4, padreId: '10101500' },
    { codigo: '10101516', nombre: 'Guayaba', nivel: 4, padreId: '10101500' },
    { codigo: '10101517', nombre: 'Pitahaya', nivel: 4, padreId: '10101500' },
    { codigo: '10101518', nombre: 'Aguacate', nivel: 4, padreId: '10101500' },
    { codigo: '10101600', nombre: 'Hortalizas y verduras', nivel: 3, padreId: '10100000' },
    { codigo: '10101601', nombre: 'Tomate', nivel: 4, padreId: '10101600' },
    { codigo: '10101602', nombre: 'Cebolla cabezona', nivel: 4, padreId: '10101600' },
    { codigo: '10101603', nombre: 'Cebolla larga', nivel: 4, padreId: '10101600' },
    { codigo: '10101604', nombre: 'Zanahoria', nivel: 4, padreId: '10101600' },
    { codigo: '10101605', nombre: 'Papa', nivel: 4, padreId: '10101600' },
    { codigo: '10101606', nombre: 'Yuca', nivel: 4, padreId: '10101600' },
    { codigo: '10101607', nombre: 'Plátano', nivel: 4, padreId: '10101600' },
    { codigo: '10101608', nombre: 'Ahuyama', nivel: 4, padreId: '10101600' },
    { codigo: '10101609', nombre: 'Lechuga', nivel: 4, padreId: '10101600' },
    { codigo: '10101610', nombre: 'Repollo', nivel: 4, padreId: '10101600' },
    { codigo: '10101611', nombre: 'Brócoli', nivel: 4, padreId: '10101600' },
    { codigo: '10101612', nombre: 'Coliflor', nivel: 4, padreId: '10101600' },
    { codigo: '10101613', nombre: 'Espinaca', nivel: 4, padreId: '10101600' },
    { codigo: '10101614', nombre: 'Remolacha', nivel: 4, padreId: '10101600' },
    { codigo: '10101615', nombre: 'Pepino', nivel: 4, padreId: '10101600' },
    { codigo: '10101616', nombre: 'Calabacín', nivel: 4, padreId: '10101600' },
    { codigo: '10101617', nombre: 'Pimentón', nivel: 4, padreId: '10101600' },
    { codigo: '10101618', nombre: 'Arveja', nivel: 4, padreId: '10101600' },
    { codigo: '10101619', nombre: 'Habichuela', nivel: 4, padreId: '10101600' },
    { codigo: '10101620', nombre: 'Maíz mazorca', nivel: 4, padreId: '10101600' },
    { codigo: '10101700', nombre: 'Cereales y granos', nivel: 3, padreId: '10100000' },
    { codigo: '10101701', nombre: 'Arroz', nivel: 4, padreId: '10101700' },
    { codigo: '10101702', nombre: 'Maíz', nivel: 4, padreId: '10101700' },
    { codigo: '10101703', nombre: 'Fríjol', nivel: 4, padreId: '10101700' },
    { codigo: '10101704', nombre: 'Lenteja', nivel: 4, padreId: '10101700' },
    { codigo: '10101705', nombre: 'Garbanzo', nivel: 4, padreId: '10101700' },
    { codigo: '10101706', nombre: 'Trigo', nivel: 4, padreId: '10101700' },
    { codigo: '10101707', nombre: 'Cebada', nivel: 4, padreId: '10101700' },
    { codigo: '10101708', nombre: 'Avena', nivel: 4, padreId: '10101700' },
    { codigo: '10101709', nombre: 'Quinua', nivel: 4, padreId: '10101700' },
    { codigo: '20000000', nombre: 'Productos alimenticios preparados', nivel: 1, padreId: null },
    { codigo: '20100000', nombre: 'Productos lácteos y huevos', nivel: 2, padreId: '20000000' },
    { codigo: '20101500', nombre: 'Leche', nivel: 3, padreId: '20100000' },
    { codigo: '20101501', nombre: 'Leche entera', nivel: 4, padreId: '20101500' },
    { codigo: '20101502', nombre: 'Leche semidescremada', nivel: 4, padreId: '20101500' },
    { codigo: '20101600', nombre: 'Queso', nivel: 3, padreId: '20100000' },
    { codigo: '20101601', nombre: 'Queso campesino', nivel: 4, padreId: '20101600' },
    { codigo: '20101602', nombre: 'Queso mozzarella', nivel: 4, padreId: '20101600' },
    { codigo: '20101700', nombre: 'Yogur', nivel: 3, padreId: '20100000' },
    { codigo: '20101701', nombre: 'Yogur natural', nivel: 4, padreId: '20101700' },
    { codigo: '20101800', nombre: 'Huevos', nivel: 3, padreId: '20100000' },
    { codigo: '20101801', nombre: 'Huevo de gallina', nivel: 4, padreId: '20101800' },
    { codigo: '20200000', nombre: 'Carnes y aves', nivel: 2, padreId: '20000000' },
    { codigo: '20201500', nombre: 'Carne de res', nivel: 3, padreId: '20200000' },
    { codigo: '20201501', nombre: 'Carne de res sin hueso', nivel: 4, padreId: '20201500' },
    { codigo: '20201600', nombre: 'Carne de cerdo', nivel: 3, padreId: '20200000' },
    { codigo: '20201601', nombre: 'Carne de cerdo', nivel: 4, padreId: '20201600' },
    { codigo: '20201700', nombre: 'Pollo', nivel: 3, padreId: '20200000' },
    { codigo: '20201701', nombre: 'Pollo entero', nivel: 4, padreId: '20201700' },
    { codigo: '20201702', nombre: 'Pechuga de pollo', nivel: 4, padreId: '20201700' },
    { codigo: '20201800', nombre: 'Pescado', nivel: 3, padreId: '20200000' },
    { codigo: '20201801', nombre: 'Pescado fresco', nivel: 4, padreId: '20201800' },
    { codigo: '20300000', nombre: 'Aceites y grasas', nivel: 2, padreId: '20000000' },
    { codigo: '20301500', nombre: 'Aceite vegetal', nivel: 3, padreId: '20300000' },
    { codigo: '20301501', nombre: 'Aceite de palma', nivel: 4, padreId: '20301500' },
    { codigo: '20301502', nombre: 'Aceite de girasol', nivel: 4, padreId: '20301500' },
    { codigo: '20400000', nombre: 'Endulzantes y confitería', nivel: 2, padreId: '20000000' },
    { codigo: '20401500', nombre: 'Azúcar', nivel: 3, padreId: '20400000' },
    { codigo: '20401501', nombre: 'Azúcar blanca', nivel: 4, padreId: '20401500' },
    { codigo: '20401502', nombre: 'Panela', nivel: 4, padreId: '20401500' },
    { codigo: '20500000', nombre: 'Productos de panadería', nivel: 2, padreId: '20000000' },
    { codigo: '20501500', nombre: 'Pan', nivel: 3, padreId: '20500000' },
    { codigo: '20501501', nombre: 'Pan blanco', nivel: 4, padreId: '20501500' },
    { codigo: '20501600', nombre: 'Galletas', nivel: 3, padreId: '20500000' },
    { codigo: '20501601', nombre: 'Galletas de sal', nivel: 4, padreId: '20501600' },
  ];

  // ============================================================
  // SIPSA - Clasificación de productos agrícolas Colombia
  // ============================================================
  const sipsaData = [
    { codigo: 'F001', nombre: 'Banano', categoria: 'fruta' },
    { codigo: 'F002', nombre: 'Manzana', categoria: 'fruta' },
    { codigo: 'F003', nombre: 'Naranja', categoria: 'fruta' },
    { codigo: 'F004', nombre: 'Papaya', categoria: 'fruta' },
    { codigo: 'F005', nombre: 'Mango', categoria: 'fruta' },
    { codigo: 'F006', nombre: 'Piña', categoria: 'fruta' },
    { codigo: 'F007', nombre: 'Fresa', categoria: 'fruta' },
    { codigo: 'F008', nombre: 'Limón', categoria: 'fruta' },
    { codigo: 'F009', nombre: 'Mandarina', categoria: 'fruta' },
    { codigo: 'F010', nombre: 'Uva', categoria: 'fruta' },
    { codigo: 'F011', nombre: 'Patilla/Sandía', categoria: 'fruta' },
    { codigo: 'F012', nombre: 'Melón', categoria: 'fruta' },
    { codigo: 'F013', nombre: 'Guanábana', categoria: 'fruta' },
    { codigo: 'F014', nombre: 'Lulo', categoria: 'fruta' },
    { codigo: 'F015', nombre: 'Maracuyá', categoria: 'fruta' },
    { codigo: 'F016', nombre: 'Guayaba', categoria: 'fruta' },
    { codigo: 'F017', nombre: 'Pitahaya', categoria: 'fruta' },
    { codigo: 'F018', nombre: 'Aguacate', categoria: 'fruta' },
    { codigo: 'H001', nombre: 'Tomate', categoria: 'hortaliza' },
    { codigo: 'H002', nombre: 'Cebolla cabezona', categoria: 'hortaliza' },
    { codigo: 'H003', nombre: 'Cebolla larga', categoria: 'hortaliza' },
    { codigo: 'H004', nombre: 'Zanahoria', categoria: 'hortaliza' },
    { codigo: 'H005', nombre: 'Papa', categoria: 'hortaliza' },
    { codigo: 'H006', nombre: 'Yuca', categoria: 'hortaliza' },
    { codigo: 'H007', nombre: 'Plátano', categoria: 'hortaliza' },
    { codigo: 'H008', nombre: 'Ahuyama', categoria: 'hortaliza' },
    { codigo: 'H009', nombre: 'Lechuga', categoria: 'hortaliza' },
    { codigo: 'H010', nombre: 'Repollo', categoria: 'hortaliza' },
    { codigo: 'H011', nombre: 'Brócoli', categoria: 'hortaliza' },
    { codigo: 'H012', nombre: 'Coliflor', categoria: 'hortaliza' },
    { codigo: 'H013', nombre: 'Espinaca', categoria: 'hortaliza' },
    { codigo: 'H014', nombre: 'Remolacha', categoria: 'hortaliza' },
    { codigo: 'H015', nombre: 'Pepino', categoria: 'hortaliza' },
    { codigo: 'H016', nombre: 'Calabacín', categoria: 'hortaliza' },
    { codigo: 'H017', nombre: 'Pimentón', categoria: 'hortaliza' },
    { codigo: 'H018', nombre: 'Arveja', categoria: 'hortaliza' },
    { codigo: 'H019', nombre: 'Habichuela', categoria: 'hortaliza' },
    { codigo: 'H020', nombre: 'Maíz mazorca', categoria: 'hortaliza' },
    { codigo: 'G001', nombre: 'Arroz', categoria: 'granos' },
    { codigo: 'G002', nombre: 'Maíz', categoria: 'granos' },
    { codigo: 'G003', nombre: 'Fríjol', categoria: 'granos' },
    { codigo: 'G004', nombre: 'Lenteja', categoria: 'granos' },
    { codigo: 'G005', nombre: 'Garbanzo', categoria: 'granos' },
    { codigo: 'G006', nombre: 'Quinua', categoria: 'granos' },
    { codigo: 'L001', nombre: 'Leche entera', categoria: 'lacteo' },
    { codigo: 'L002', nombre: 'Queso campesino', categoria: 'lacteo' },
    { codigo: 'L003', nombre: 'Yogur natural', categoria: 'lacteo' },
    { codigo: 'P001', nombre: 'Huevo de gallina', categoria: 'huevos' },
    { codigo: 'P002', nombre: 'Carne de res', categoria: 'carnes' },
    { codigo: 'P003', nombre: 'Pollo', categoria: 'carnes' },
    { codigo: 'P004', nombre: 'Pescado', categoria: 'carnes' },
    { codigo: 'A001', nombre: 'Aceite vegetal', categoria: 'procesado' },
    { codigo: 'A002', nombre: 'Azúcar', categoria: 'procesado' },
    { codigo: 'A003', nombre: 'Panela', categoria: 'procesado' },
    { codigo: 'A004', nombre: 'Pan', categoria: 'procesado' },
    { codigo: 'A005', nombre: 'Sal', categoria: 'procesado' },
    { codigo: 'A006', nombre: 'Miel', categoria: 'procesado' },
  ];

  // ============================================================
  // ProductoBase - Productos típicos PAE
  // ============================================================
  const productosData = [
    {
      nombre: 'Banano',
      categoria: 'fruta',
      unidadMedidaDefecto: 'kg',
      codigoUnspsc: '10101501',
      codigoSipsa: 'F001',
      atributosSchema: { color: ['verde', 'maduro'], procedencia: ['nacional'] },
      certificacionesRequeridas: ['BPA'],
      fotoUrl: '/img/productos/banano.jpg',
    },
    {
      nombre: 'Manzana',
      categoria: 'fruta',
      unidadMedidaDefecto: 'kg',
      codigoUnspsc: '10101502',
      codigoSipsa: 'F002',
      atributosSchema: { variedad: ['roja', 'verde'], procedencia: ['nacional', 'importada'] },
      certificacionesRequeridas: ['BPA'],
      fotoUrl: '/img/productos/manzana.jpg',
    },
    {
      nombre: 'Naranja',
      categoria: 'fruta',
      unidadMedidaDefecto: 'kg',
      codigoUnspsc: '10101503',
      codigoSipsa: 'F003',
      atributosSchema: { variedad: ['valencia', 'común'], procedencia: ['nacional'] },
      certificacionesRequeridas: ['BPA'],
      fotoUrl: '/img/productos/naranja.jpg',
    },
    {
      nombre: 'Papaya',
      categoria: 'fruta',
      unidadMedidaDefecto: 'unidad',
      codigoUnspsc: '10101504',
      codigoSipsa: 'F004',
      atributosSchema: { tamanio: ['pequeña', 'mediana', 'grande'], procedencia: ['nacional'] },
      certificacionesRequeridas: ['BPA'],
      fotoUrl: '/img/productos/papaya.jpg',
    },
    {
      nombre: 'Mango',
      categoria: 'fruta',
      unidadMedidaDefecto: 'kg',
      codigoUnspsc: '10101505',
      codigoSipsa: 'F005',
      atributosSchema: { variedad: ['tommy', 'sufaida', 'hilacha'], procedencia: ['nacional'] },
      certificacionesRequeridas: ['BPA'],
      fotoUrl: '/img/productos/mango.jpg',
    },
    {
      nombre: 'Piña',
      categoria: 'fruta',
      unidadMedidaDefecto: 'unidad',
      codigoUnspsc: '10101506',
      codigoSipsa: 'F006',
      atributosSchema: { variedad: ['gold', 'perolera'], procedencia: ['nacional'] },
      certificacionesRequeridas: ['BPA'],
      fotoUrl: '/img/productos/pina.jpg',
    },
    {
      nombre: 'Fresa',
      categoria: 'fruta',
      unidadMedidaDefecto: 'kg',
      codigoUnspsc: '10101507',
      codigoSipsa: 'F007',
      atributosSchema: { presentacion: ['entera', 'congelada'], procedencia: ['nacional'] },
      certificacionesRequeridas: ['BPA'],
      fotoUrl: '/img/productos/fresa.jpg',
    },
    {
      nombre: 'Limón',
      categoria: 'fruta',
      unidadMedidaDefecto: 'kg',
      codigoUnspsc: '10101508',
      codigoSipsa: 'F008',
      atributosSchema: { variedad: ['común', 'mandarino'], procedencia: ['nacional'] },
      certificacionesRequeridas: ['BPA'],
      fotoUrl: '/img/productos/limon.jpg',
    },
    {
      nombre: 'Mandarina',
      categoria: 'fruta',
      unidadMedidaDefecto: 'kg',
      codigoUnspsc: '10101509',
      codigoSipsa: 'F009',
      atributosSchema: { variedad: ['arrayana', 'común'], procedencia: ['nacional'] },
      certificacionesRequeridas: ['BPA'],
      fotoUrl: '/img/productos/mandarina.jpg',
    },
    {
      nombre: 'Aguacate',
      categoria: 'fruta',
      unidadMedidaDefecto: 'kg',
      codigoUnspsc: '10101518',
      codigoSipsa: 'F018',
      atributosSchema: { variedad: ['hass', 'criollo', 'papelillo'], procedencia: ['nacional'] },
      certificacionesRequeridas: ['BPA'],
      fotoUrl: '/img/productos/aguacate.jpg',
    },
    {
      nombre: 'Tomate',
      categoria: 'verdura',
      unidadMedidaDefecto: 'kg',
      codigoUnspsc: '10101601',
      codigoSipsa: 'H001',
      atributosSchema: { tipo: ['chonto', 'larga vida', 'cherry'], procedencia: ['nacional'] },
      certificacionesRequeridas: ['BPA'],
      fotoUrl: '/img/productos/tomate.jpg',
    },
    {
      nombre: 'Cebolla Cabezona',
      categoria: 'verdura',
      unidadMedidaDefecto: 'kg',
      codigoUnspsc: '10101602',
      codigoSipsa: 'H002',
      atributosSchema: { color: ['blanca', 'roja'], procedencia: ['nacional'] },
      certificacionesRequeridas: ['BPA'],
      fotoUrl: '/img/productos/cebolla-cabezona.jpg',
    },
    {
      nombre: 'Cebolla Larga',
      categoria: 'verdura',
      unidadMedidaDefecto: 'kg',
      codigoUnspsc: '10101603',
      codigoSipsa: 'H003',
      atributosSchema: { procedencia: ['nacional'] },
      certificacionesRequeridas: ['BPA'],
      fotoUrl: '/img/productos/cebolla-larga.jpg',
    },
    {
      nombre: 'Zanahoria',
      categoria: 'verdura',
      unidadMedidaDefecto: 'kg',
      codigoUnspsc: '10101604',
      codigoSipsa: 'H004',
      atributosSchema: { procedencia: ['nacional'] },
      certificacionesRequeridas: ['BPA'],
      fotoUrl: '/img/productos/zanahoria.jpg',
    },
    {
      nombre: 'Papa',
      categoria: 'verdura',
      unidadMedidaDefecto: 'kg',
      codigoUnspsc: '10101605',
      codigoSipsa: 'H005',
      atributosSchema: { variedad: ['sabanera', 'pastusa', 'criolla', 'única'], procedencia: ['nacional'] },
      certificacionesRequeridas: ['BPA'],
      fotoUrl: '/img/productos/papa.jpg',
    },
    {
      nombre: 'Yuca',
      categoria: 'verdura',
      unidadMedidaDefecto: 'kg',
      codigoUnspsc: '10101606',
      codigoSipsa: 'H006',
      atributosSchema: { procedencia: ['nacional'] },
      certificacionesRequeridas: ['BPA'],
      fotoUrl: '/img/productos/yuca.jpg',
    },
    {
      nombre: 'Plátano',
      categoria: 'verdura',
      unidadMedidaDefecto: 'kg',
      codigoUnspsc: '10101607',
      codigoSipsa: 'H007',
      atributosSchema: { tipo: ['verde', 'maduro', 'hartón'], procedencia: ['nacional'] },
      certificacionesRequeridas: ['BPA'],
      fotoUrl: '/img/productos/platano.jpg',
    },
    {
      nombre: 'Ahuyama',
      categoria: 'verdura',
      unidadMedidaDefecto: 'kg',
      codigoUnspsc: '10101608',
      codigoSipsa: 'H008',
      atributosSchema: { procedencia: ['nacional'] },
      certificacionesRequeridas: ['BPA'],
      fotoUrl: '/img/productos/ahuyama.jpg',
    },
    {
      nombre: 'Lechuga',
      categoria: 'verdura',
      unidadMedidaDefecto: 'unidad',
      codigoUnspsc: '10101609',
      codigoSipsa: 'H009',
      atributosSchema: { tipo: ['crespa', 'batavia', 'romana'], procedencia: ['nacional'] },
      certificacionesRequeridas: ['BPA'],
      fotoUrl: '/img/productos/lechuga.jpg',
    },
    {
      nombre: 'Pimentón',
      categoria: 'verdura',
      unidadMedidaDefecto: 'kg',
      codigoUnspsc: '10101617',
      codigoSipsa: 'H017',
      atributosSchema: { color: ['rojo', 'verde', 'amarillo'], procedencia: ['nacional'] },
      certificacionesRequeridas: ['BPA'],
      fotoUrl: '/img/productos/pimenton.jpg',
    },
    {
      nombre: 'Arroz',
      categoria: 'granos',
      unidadMedidaDefecto: 'kg',
      codigoUnspsc: '10101701',
      codigoSipsa: 'G001',
      atributosSchema: { tipo: ['blanco', 'integral'], procedencia: ['nacional'] },
      certificacionesRequeridas: [],
      fotoUrl: '/img/productos/arroz.jpg',
    },
    {
      nombre: 'Fríjol',
      categoria: 'granos',
      unidadMedidaDefecto: 'kg',
      codigoUnspsc: '10101703',
      codigoSipsa: 'G003',
      atributosSchema: { variedad: ['cargamanto', 'bola roja', 'negro'], procedencia: ['nacional'] },
      certificacionesRequeridas: [],
      fotoUrl: '/img/productos/frijol.jpg',
    },
    {
      nombre: 'Lenteja',
      categoria: 'granos',
      unidadMedidaDefecto: 'kg',
      codigoUnspsc: '10101704',
      codigoSipsa: 'G004',
      atributosSchema: { procedencia: ['nacional', 'importada'] },
      certificacionesRequeridas: [],
      fotoUrl: '/img/productos/lenteja.jpg',
    },
    {
      nombre: 'Quinua',
      categoria: 'granos',
      unidadMedidaDefecto: 'kg',
      codigoUnspsc: '10101709',
      codigoSipsa: 'G006',
      atributosSchema: { variedad: ['blanca', 'roja', 'negra'], procedencia: ['nacional'] },
      certificacionesRequeridas: ['organico'],
      fotoUrl: '/img/productos/quinua.jpg',
    },
    {
      nombre: 'Leche Entera',
      categoria: 'lacteo',
      unidadMedidaDefecto: 'litro',
      codigoUnspsc: '20101501',
      codigoSipsa: 'L001',
      atributosSchema: { tipo: ['pasteurizada', 'ultrapasteurizada'], procedencia: ['nacional'] },
      certificacionesRequeridas: ['invima'],
      fotoUrl: '/img/productos/leche.jpg',
    },
    {
      nombre: 'Queso Campesino',
      categoria: 'lacteo',
      unidadMedidaDefecto: 'kg',
      codigoUnspsc: '20101601',
      codigoSipsa: 'L002',
      atributosSchema: { presentacion: ['entero', 'lonjas'], procedencia: ['nacional'] },
      certificacionesRequeridas: ['invima'],
      fotoUrl: '/img/productos/queso.jpg',
    },
    {
      nombre: 'Yogur Natural',
      categoria: 'lacteo',
      unidadMedidaDefecto: 'litro',
      codigoUnspsc: '20101701',
      codigoSipsa: 'L003',
      atributosSchema: { tipo: ['natural', 'con fruta'], procedencia: ['nacional'] },
      certificacionesRequeridas: ['invima'],
      fotoUrl: '/img/productos/yogur.jpg',
    },
    {
      nombre: 'Huevo de Gallina',
      categoria: 'carnes',
      unidadMedidaDefecto: 'unidad',
      codigoUnspsc: '20101801',
      codigoSipsa: 'P001',
      atributosSchema: { tipo: ['blanco', 'campesino'], procedencia: ['nacional'] },
      certificacionesRequeridas: ['invima'],
      fotoUrl: '/img/productos/huevo.jpg',
    },
    {
      nombre: 'Carne de Res',
      categoria: 'carnes',
      unidadMedidaDefecto: 'kg',
      codigoUnspsc: '20201501',
      codigoSipsa: 'P002',
      atributosSchema: { corte: ['muchacho', 'muchacho redondo', 'lomo', 'costilla'], procedencia: ['nacional'] },
      certificacionesRequeridas: ['invima'],
      fotoUrl: '/img/productos/carne-res.jpg',
    },
    {
      nombre: 'Pollo',
      categoria: 'carnes',
      unidadMedidaDefecto: 'kg',
      codigoUnspsc: '20201701',
      codigoSipsa: 'P003',
      atributosSchema: { tipo: ['entero', 'pechuga', 'muslo'], procedencia: ['nacional'] },
      certificacionesRequeridas: ['invima'],
      fotoUrl: '/img/productos/pollo.jpg',
    },
    {
      nombre: 'Pescado Fresco',
      categoria: 'carnes',
      unidadMedidaDefecto: 'kg',
      codigoUnspsc: '20201801',
      codigoSipsa: 'P004',
      atributosSchema: { especie: ['tilapia', 'mojarra', 'bagre', 'bocachico'], procedencia: ['nacional'] },
      certificacionesRequeridas: ['invima'],
      fotoUrl: '/img/productos/pescado.jpg',
    },
    {
      nombre: 'Aceite Vegetal',
      categoria: 'procesado',
      unidadMedidaDefecto: 'litro',
      codigoUnspsc: '20301501',
      codigoSipsa: 'A001',
      atributosSchema: { tipo: ['palma', 'girasol', 'soya'], procedencia: ['nacional'] },
      certificacionesRequeridas: ['invima'],
      fotoUrl: '/img/productos/aceite.jpg',
    },
    {
      nombre: 'Azúcar',
      categoria: 'procesado',
      unidadMedidaDefecto: 'kg',
      codigoUnspsc: '20401501',
      codigoSipsa: 'A002',
      atributosSchema: { tipo: ['blanca', 'morena'], procedencia: ['nacional'] },
      certificacionesRequeridas: [],
      fotoUrl: '/img/productos/azucar.jpg',
    },
    {
      nombre: 'Panela',
      categoria: 'procesado',
      unidadMedidaDefecto: 'kg',
      codigoUnspsc: '20401502',
      codigoSipsa: 'A003',
      atributosSchema: { presentacion: ['cuadro', 'redonda', 'pulverizada'], procedencia: ['nacional'] },
      certificacionesRequeridas: [],
      fotoUrl: '/img/productos/panela.jpg',
    },
    {
      nombre: 'Pan',
      categoria: 'procesado',
      unidadMedidaDefecto: 'unidad',
      codigoUnspsc: '20501501',
      codigoSipsa: 'A004',
      atributosSchema: { tipo: ['blanco', 'integral', 'campesino'], procedencia: ['nacional'] },
      certificacionesRequeridas: [],
      fotoUrl: '/img/productos/pan.jpg',
    },
    {
      nombre: 'Sal',
      categoria: 'procesado',
      unidadMedidaDefecto: 'kg',
      codigoUnspsc: null,
      codigoSipsa: 'A005',
      atributosSchema: { tipo: ['fina', 'gruesa', 'marina'], procedencia: ['nacional'] },
      certificacionesRequeridas: ['invima'],
      fotoUrl: '/img/productos/sal.jpg',
    },
    {
      nombre: 'Miel de Abejas',
      categoria: 'miel',
      unidadMedidaDefecto: 'kg',
      codigoUnspsc: null,
      codigoSipsa: 'A006',
      atributosSchema: { tipo: ['natural', 'orgánica'], procedencia: ['nacional'] },
      certificacionesRequeridas: ['invima'],
      fotoUrl: '/img/productos/miel.jpg',
    },
  ];

  console.log('Insertando UNSPSC...');
  for (const u of unspscData) {
    await prisma.unidadUnspsc.upsert({
      where: { codigo: u.codigo },
      update: {},
      create: u,
    });
  }
  console.log(`  ${unspscData.length} códigos UNSPSC insertados`);

  console.log('Insertando SIPSA...');
  for (const s of sipsaData) {
    await prisma.unidadSipsa.upsert({
      where: { codigo: s.codigo },
      update: {},
      create: s,
    });
  }
  console.log(`  ${sipsaData.length} códigos SIPSA insertados`);

  console.log('Insertando Productos Base...');
  for (const p of productosData) {
    const existing = await prisma.productoBase.findFirst({
      where: { tenantId: null, nombre: p.nombre },
    });
    if (!existing) {
      await prisma.productoBase.create({
        data: {
          nombre: p.nombre,
          categoria: p.categoria,
          unidadMedidaDefecto: p.unidadMedidaDefecto,
          codigoUnspsc: p.codigoUnspsc,
          codigoSipsa: p.codigoSipsa,
          atributosSchema: p.atributosSchema,
          certificacionesRequeridas: p.certificacionesRequeridas,
          fotoUrl: p.fotoUrl,
          activo: true,
          createdBy: createdBy,
        },
      });
    }
  }
  console.log(`  ${productosData.length} productos base insertados`);

  console.log('Catálogo base sembrado exitosamente');
}

main()
  .catch((e) => {
    console.error('Error sembrando catálogo:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
