-- Create Pais table
CREATE TABLE "paises" (
    "codigo" VARCHAR(2) NOT NULL,
    "nombre" VARCHAR(100) NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "paises_pkey" PRIMARY KEY ("codigo")
);

-- Add pais_codigo column to departamentos
ALTER TABLE "departamentos" ADD COLUMN "pais_codigo" VARCHAR(2);

-- Set default for existing rows
UPDATE "departamentos" SET "pais_codigo" = 'CO';

-- Now make it NOT NULL
ALTER TABLE "departamentos" ALTER COLUMN "pais_codigo" SET NOT NULL;

-- Add foreign key
ALTER TABLE "departamentos" ADD CONSTRAINT "departamentos_pais_codigo_fkey" FOREIGN KEY ("pais_codigo") REFERENCES "paises"("codigo");

-- Insert Colombia
INSERT INTO "paises" ("codigo", "nombre") VALUES ('CO', 'Colombia') ON CONFLICT ("codigo") DO NOTHING;

-- Insert all 32 Colombian departments
INSERT INTO "paises" ("codigo", "nombre") VALUES
  ('AF', 'Afganistán'),
  ('AL', 'Albania'),
  ('DE', 'Alemania'),
  ('AD', 'Andorra'),
  ('AO', 'Angola'),
  ('AG', 'Antigua y Barbuda'),
  ('SA', 'Arabia Saudita'),
  ('DZ', 'Argelia'),
  ('AR', 'Argentina'),
  ('AM', 'Armenia'),
  ('AU', 'Australia'),
  ('AT', 'Austria'),
  ('AZ', 'Azerbaiyán'),
  ('BS', 'Bahamas'),
  ('BH', 'Baréin'),
  ('BD', 'Bangladés'),
  ('BB', 'Barbados'),
  ('BE', 'Bélgica'),
  ('BZ', 'Belice'),
  ('BJ', 'Benín'),
  ('BY', 'Bielorrusia'),
  ('MM', 'Birmania'),
  ('BO', 'Bolivia'),
  ('BA', 'Bosnia y Herzegovina'),
  ('BW', 'Botsuana'),
  ('BR', 'Brasil'),
  ('BN', 'Brunéi'),
  ('BG', 'Bulgaria'),
  ('BF', 'Burkina Faso'),
  ('BI', 'Burundi'),
  ('BT', 'Bután'),
  ('CV', 'Cabo Verde'),
  ('KH', 'Camboya'),
  ('CM', 'Camerún'),
  ('CA', 'Canadá'),
  ('QA', 'Catar'),
  ('TD', 'Chad'),
  ('CL', 'Chile'),
  ('CN', 'China'),
  ('CY', 'Chipre'),
  ('VA', 'Ciudad del Vaticano'),
  ('CO', 'Colombia'),
  ('KM', 'Comoras'),
  ('CG', 'Congo'),
  ('CD', 'República Democrática del Congo'),
  ('KP', 'Corea del Norte'),
  ('KR', 'Corea del Sur'),
  ('CI', 'Costa de Marfil'),
  ('CR', 'Costa Rica'),
  ('HR', 'Croacia'),
  ('CU', 'Cuba'),
  ('DK', 'Dinamarca'),
  ('DM', 'Dominica'),
  ('EC', 'Ecuador'),
  ('EG', 'Egipto'),
  ('SV', 'El Salvador'),
  ('AE', 'Emiratos Árabes Unidos'),
  ('ER', 'Eritrea'),
  ('SK', 'Eslovaquia'),
  ('SI', 'Eslovenia'),
  ('ES', 'España'),
  ('US', 'Estados Unidos'),
  ('EE', 'Estonia'),
  ('ET', 'Etiopía'),
  ('PH', 'Filipinas'),
  ('FI', 'Finlandia'),
  ('FJ', 'Fiyi'),
  ('FR', 'Francia'),
  ('GA', 'Gabón'),
  ('GM', 'Gambia'),
  ('GE', 'Georgia'),
  ('GH', 'Ghana'),
  ('GD', 'Granada'),
  ('GR', 'Grecia'),
  ('GT', 'Guatemala'),
  ('GN', 'Guinea'),
  ('GW', 'Guinea-Bisáu'),
  ('GQ', 'Guinea Ecuatorial'),
  ('GY', 'Guyana'),
  ('HT', 'Haití'),
  ('HN', 'Honduras'),
  ('HU', 'Hungría'),
  ('IN', 'India'),
  ('ID', 'Indonesia'),
  ('IQ', 'Irak'),
  ('IR', 'Irán'),
  ('IE', 'Irlanda'),
  ('IS', 'Islandia'),
  ('IL', 'Israel'),
  ('IT', 'Italia'),
  ('JM', 'Jamaica'),
  ('JP', 'Japón'),
  ('JO', 'Jordania'),
  ('KZ', 'Kazajistán'),
  ('KE', 'Kenia'),
  ('KG', 'Kirguistán'),
  ('KI', 'Kiribati'),
  ('KW', 'Kuwait'),
  ('LA', 'Laos'),
  ('LS', 'Lesoto'),
  ('LV', 'Letonia'),
  ('LB', 'Líbano'),
  ('LR', 'Liberia'),
  ('LY', 'Libia'),
  ('LI', 'Liechtenstein'),
  ('LT', 'Lituania'),
  ('LU', 'Luxemburgo'),
  ('MK', 'Macedonia del Norte'),
  ('MG', 'Madagascar'),
  ('MY', 'Malasia'),
  ('MW', 'Malaui'),
  ('MV', 'Maldivas'),
  ('ML', 'Malí'),
  ('MT', 'Malta'),
  ('MA', 'Marruecos'),
  ('MU', 'Mauricio'),
  ('MR', 'Mauritania'),
  ('MX', 'México'),
  ('FM', 'Micronesia'),
  ('MD', 'Moldavia'),
  ('MC', 'Mónaco'),
  ('MN', 'Mongolia'),
  ('ME', 'Montenegro'),
  ('MZ', 'Mozambique'),
  ('NA', 'Namibia'),
  ('NR', 'Nauru'),
  ('NP', 'Nepal'),
  ('NI', 'Nicaragua'),
  ('NE', 'Níger'),
  ('NG', 'Nigeria'),
  ('NO', 'Noruega'),
  ('NZ', 'Nueva Zelanda'),
  ('OM', 'Omán'),
  ('NL', 'Países Bajos'),
  ('PK', 'Pakistán'),
  ('PW', 'Palaos'),
  ('PS', 'Palestina'),
  ('PA', 'Panamá'),
  ('PG', 'Papúa Nueva Guinea'),
  ('PY', 'Paraguay'),
  ('PE', 'Perú'),
  ('PL', 'Polonia'),
  ('PT', 'Portugal'),
  ('PR', 'Puerto Rico'),
  ('GB', 'Reino Unido'),
  ('CF', 'República Centroafricana'),
  ('CZ', 'República Checa'),
  ('DO', 'República Dominicana'),
  ('RW', 'Ruanda'),
  ('RO', 'Rumania'),
  ('RU', 'Rusia'),
  ('WS', 'Samoa'),
  ('SM', 'San Marino'),
  ('ST', 'Santo Tomé y Príncipe'),
  ('SN', 'Senegal'),
  ('RS', 'Serbia'),
  ('SC', 'Seychelles'),
  ('SL', 'Sierra Leona'),
  ('SG', 'Singapur'),
  ('SY', 'Siria'),
  ('SO', 'Somalia'),
  ('LK', 'Sri Lanka'),
  ('SZ', 'Suazilandia'),
  ('ZA', 'Sudáfrica'),
  ('SD', 'Sudán'),
  ('SS', 'Sudán del Sur'),
  ('SE', 'Suecia'),
  ('CH', 'Suiza'),
  ('SR', 'Surinam'),
  ('TH', 'Tailandia'),
  ('TW', 'Taiwán'),
  ('TZ', 'Tanzania'),
  ('TJ', 'Tayikistán'),
  ('TL', 'Timor Oriental'),
  ('TG', 'Togo'),
  ('TO', 'Tonga'),
  ('TT', 'Trinidad y Tobago'),
  ('TN', 'Túnez'),
  ('TM', 'Turkmenistán'),
  ('TR', 'Turquía'),
  ('TV', 'Tuvalu'),
  ('UA', 'Ucrania'),
  ('UG', 'Uganda'),
  ('UY', 'Uruguay'),
  ('UZ', 'Uzbekistán'),
  ('VU', 'Vanuatu'),
  ('VE', 'Venezuela'),
  ('VN', 'Vietnam'),
  ('YE', 'Yemen'),
  ('DJ', 'Yibuti'),
  ('ZM', 'Zambia'),
  ('ZW', 'Zimbabue')
ON CONFLICT ("codigo") DO NOTHING;

-- Update all existing departments to link to Colombia
UPDATE "departamentos" SET "pais_codigo" = 'CO' WHERE "pais_codigo" IS NULL;

-- Record this migration
INSERT INTO "_prisma_migrations" ("id", "checksum", "finished_at", "migration_name", "logs", "rolled_back_at", "started_at", "applied_steps_count")
VALUES (
  'add-paises-manual',
  'manual',
  NOW(),
  '20250717_add_paises',
  'Manual migration: add paises table, link departamentos to CO',
  NULL,
  NOW(),
  1
);
