http:
  routers:
    api:
      rule: "Host(`api.pae.local`)"
      service: api
      entryPoints:
        - web
    web:
      rule: "Host(`app.pae.local`)"
      service: web
      entryPoints:
        - web

  services:
    api:
      loadBalancer:
        servers:
          - url: "http://api:3001"
    web:
      loadBalancer:
        servers:
          - url: "http://web:3000"

entryPoints:
  web:
    address: ":80"
